### ISSUE TITLE
Текст для игры - пояснения рефлексов для карточек (до 01.04)

### ISSUE THREAD

**Issue by Visherrrix** [Visherrrix/Int32ensiv#10]
Краткие описания рефлекса каждого из выбранных разработчиками уровней (пока 3 шт.) - т.е. нужно описать происходящее в цепочке (можно взять за основу описания рефлексов для уровней):
Безусловные:
-Отдергивание руки при касании чайника 
-Расширение, уменьшение зрачка под воздействием света
-Реакция на щекотку пятки пером 
Запас безусловного: Когда теряем равновесие пытаемся удержаться/схватиться за что то
Условные:
-Когда человек видит красный на светофоре, он останавливается
-При переходе дороги человек смотрит по сторонам
-Собака Павлова пускает слюни при звуке колокольчика
Запас условного: при звонке с урока дети быстро собираются домой/на перемену

Пример переработки:
-Отдергивание руки при прикосновении к горячему чайнику
-под воздействием света зрачок меняет размер

**Comment by Miracl9e9** [comment]
### Рефлексы на уровнях:
### Безусловные:
- Отдергивание руки при касании горячего чайника.
- Изменение размера зрачка под воздействием света.
- Реакция на щекотку пятки пером.
Запас безусловного рефлекса: При потере равновесия попытка удержаться или схватиться за что-то.
Условные:
- Остановка при виде красного на светофоре.
- Обращение взгляда по сторонам при переходе дороги.
- Собака Павлова начинает слюнить при звуке колокольчика.

> Запас условного рефлекса: Быстрое собрание детей или переход в другое место при звонке с урока
