### ISSUE TITLE
Интерфейс - фоны (до 01.04)

### ISSUE THREAD

**Issue by Visherrrix** [Visherrrix/Int32ensiv#13]
Создать для игры фоны требуемого разработчиками размера и сочетающиеся со стилистикой игры
Фон лабораторного стола для уровней
Фон для выбора уровня
Фон загрузки

**Comment by Visherrrix** [comment]
фон 1 принят
![photo_5211207455621634455_y](https://github.com/Visherrrix/Int32ensiv/assets/147908283/9cdf6737-68cf-4bb8-949f-1d2391e7ed02)

**Comment by Visherrrix** [comment]
![photo_5211207455621635347_y](https://github.com/Visherrrix/Int32ensiv/assets/147908283/89881aa4-a75c-461e-99f4-52a0082e2c68)

**Comment by Wak1ngj** [comment]
![Фон - переход по уровням](https://github.com/Visherrrix/Int32ensiv/assets/151366972/e52b11f5-60e5-4732-be6c-1c203b6a7aa8)
