### ISSUE TITLE
Разработка сцен меню, выбора уровней, загрузки 

### ISSUE THREAD

**Issue by Arhenon** [Visherrrix/Int32ensiv#14]
Главное меню, на котором будут кнопки "Выбор уровня" и "Выйти из игры";
-Сцена с выбором одного из 3 уровней(предусмотреть возможность увеличения количество уровней до 6 и более);
-Сцена/префаб загрузки, обладающая анимацией, представленной в предыдущей задаче по разработке(можно использовать заглушки в виде фигур и т.п.).

**Comment by xwld1** [comment]
Залито в ветку, 2 сцены, префаб встроен в сцены
<img width="95" alt="1" src="https://github.com/Visherrrix/Int32ensiv/assets/159610573/dc376c4d-f628-49ae-87de-029488f44996">
<img width="386" alt="2" src="https://github.com/Visherrrix/Int32ensiv/assets/159610573/862c5f69-e1c3-4483-b799-7e0e9eb5093d">
