### ISSUE TITLE
Концепт инфографики (до 20:00 05.04)

### ISSUE THREAD

**Issue by Visherrrix** [Visherrrix/Int32ensiv#19]
Найти идею для представления блока теории (инфографики) по типу Смешариков (варианты: найти видео/придумать раскадровку или сценарий/создать видео самому или совместно с командой)
Длительности должно хватать для звучания текста инфографики

**Comment by Miracl9e9** [comment]
Рефлекс - это реакция организма на воздействие через рецепторы и нервную систему. Существуют безусловные и условные рефлексы. 

Безусловные рефлексы - это наследуемые и неизменные реакции организма на определенные воздействия внешней или внутренней среды. Пример - кошка приземляется на четыре лапы, независимо от высоты падения.

Условные рефлексы возникают в процессе развития и усвоения новых навыков. Например, собака выделяет желудочный сок при звонке, связывая звук с пищей.

Условные рефлексы формируют приобретенное поведение и привычки. Динамический стереотип - это система связей в коре полушарий, которая образуется по мере приобретения опыта.

Умение быстро реагировать на изменения окружающей среды позволяет успешно адаптироваться и жить в мире.

**Comment by Visherrrix** [comment]
сюда именно картинки надо, не текст
