### ISSUE TITLE
Текст инфографики (до 05.04)

### ISSUE THREAD

**Issue by Visherrrix** [Visherrrix/Int32ensiv#2]
[Интенсив (3).docx](https://github.com/Visherrrix/Int32ensiv/files/14796086/3.docx)
Упрощение текста инфографики
Можно сократить про пример условных рефлексов (соотнести с объемом информации о безусловных рефлексах)

**Comment by Miracl9e9** [comment]
Рефлекс - это реакция организма на воздействие через рецепторы и нервную систему. Существуют безусловные и условные рефлексы. 

Безусловные рефлексы - это наследуемые и неизменные реакции организма на определенные воздействия внешней или внутренней среды. Пример - кошка приземляется на четыре лапы, независимо от высоты падения.

Условные рефлексы возникают в процессе развития и усвоения новых навыков. Например, собака выделяет желудочный сок при звонке, связывая звук с пищей. Условные рефлексы формируют приобретенное поведение и привычки. 

Динамический стереотип - это система связей в коре полушарий, которая образуется по мере приобретения опыта.

Умение быстро реагировать на изменения окружающей среды позволяет успешно адаптироваться и жить в мире.
