### ISSUE TITLE
Текст для игры - теория (до 01.04)

### ISSUE THREAD

**Issue by Visherrrix** [Visherrrix/Int32ensiv#9]
Создание краткого текста с теорией о рефлексах для подсказки в игре
Должны поясняться безусловные и условные рефлексы, а также как работают рефлексы персонажей.

**Comment by Miracl9e9** [comment]
### Рефлексы - непроизвольные реакции организма на стимулы внешней среды. Безусловные рефлексы - инстинктивные реакции, а условные рефлексы приобретаются с опытом и обучением. 
### Рефлексы работают через передачу сигналов нервной системы.
